version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: discount_service_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - discount-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discount_service_app
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - discount-network
    volumes:
      - .:/app

volumes:
  postgres-data:

networks:
  discount-network:
    driver: bridge
